apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis
resources:
  - namespace.yaml
  - helm-release.yaml
configurations:
  - ../../../kustomizations/configure-helm-values/helm-values-from-kustomization.yaml
