apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.8.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 1h0m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
