apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis
resources:
  - ../base
configMapGenerator:
  - name: redis-values
    files:
      - values.yaml=values.yaml
patches:
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: redis
      spec:
        valuesFrom:
          - kind: ConfigMap
            name: redis-values
