# Default values
# https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml
auth:
  enabled: false
master:
  persistence:
    enabled: false
replica:
  replicaCount: 1
  persistence:
    enabled: false
