apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../base
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=values.yaml
patches:
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: cert-manager
      spec:
        valuesFrom:
          - kind: ConfigMap
            name: cert-manager-values
