apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/BuoyantIO/emojivoto/kustomize/deployment
  - ingress.yaml
patches:
  - patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: emojivoto
        annotations:
          linkerd.io/inject: enabled
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: vote-bot
        namespace: emojivoto
      spec:
        template:
          spec:
            containers:
              - name: vote-bot
                env: 
                  - name: WEB_HOST
                    value: web-svc:80
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web
        namespace: emojivoto
      spec:
        template:
          spec:
            containers:
              - name: web-svc
                env: 
                  - name: EMOJISVC_HOST
                    value: emoji-svc:8080
                  - name: VOTINGSVC_HOST
                    value: voting-svc:8080
