apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/BuoyantIO/emojivoto/kustomize/deployment
  - ingress.yaml
patches:
  - patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: emojivoto
        annotations:
          linkerd.io/inject: enabled
