apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-ingress-controller
resources:
  - ../base
configMapGenerator:
  - name: nginx-ingress-controller-values
    files:
      - values.yaml=values.yaml
patches:
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: nginx
      spec:
        valuesFrom:
          - kind: ConfigMap
            name: nginx-ingress-controller-values
