# Default values
# https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
service:
  type: NodePort
  nodePorts:
    http: 30080
    https: 30443
controller:
  config:
    enable-opentracing: "true"
    zipkin-collector-host: collector.linkerd-jaeger
