apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: central-redis
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
  interval: 2m0s
  path: ./infrastructure/redis/sandbox
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: redis
