apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: central-redis
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
    - name: linkerd
  interval: 1m0s
  path: ./infrastructure/redis/sandbox
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-catalog
  targetNamespace: redis
