apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
  interval: 2m0s
  path: ./infrastructure/cert-manager/sandbox
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-catalog
  targetNamespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: letsencrypt-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
    - name: nginx-ingress-controller
    - name: cert-manager
  interval: 2m0s
  path: ./infrastructure/cert-manager/letsencrypt-issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-catalog
  targetNamespace: letsencrypt-issuers
