apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: linkerd-jaeger
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
    - name: linkerd
  interval: 1m0s
  timeout: 3m
  path: ./infrastructure/linkerd-jaeger/sandbox
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-catalog
  targetNamespace: linkerd-jaeger
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: linkerd-jaeger
      namespace: linkerd-jaeger
