apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
  interval: 1m0s
  timeout: 3m
  path: ./infrastructure/nginx-ingress-controller/sandbox
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-catalog
  targetNamespace: nginx-ingress-controller
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: nginx
      namespace: nginx-ingress-controller
