apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-sources
  interval: 2m0s
  path: ./infrastructure/nginx-ingress-controller/sandbox
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-catalog
  targetNamespace: nginx-ingress-controller
