---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-with-source-namespace
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./kustomizations/create-namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: podinfo-source
