---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-with-helm
  namespace: flux-system
spec:
  dependsOn:
    - name: app-sources
    - name: central-redis
    - name: nginx-ingress-controller
    - name: cert-manager
  interval: 2m0s
  path: ./apps/podinfo-with-helm
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-catalog
  targetNamespace: podinfo-helm
