apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
spec:
  releaseName: linkerd
  chart:
    spec:
      chart: linkerd2
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  interval: 1h0m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
