# Emulate external repo with the app sources
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: app-catalog
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/cirano-eusebi/flux-test
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-sources
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./app-sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-catalog
  targetNamespace: flux-system
