# Emulate external repo with the infra sources
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: infra-catalog
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/cirano-eusebi/flux-test
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-sources
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./infrastructure-sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-catalog
  targetNamespace: flux-system
