---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: podinfo
  resources:
    - |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name:  podinfo
        labels:
          name: podinfo
          app: podinfo
