---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-with-source
  namespace: flux-system
spec:
  dependsOn:
    - name: podinfo-with-source-namespace
  interval: 2m0s
  path: ./kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: podinfo-source
