apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shared-sources
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
