apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
configurations:
  - ../../kustomizations/configure-helm-values/helm-values-from-kustomization.yaml
configMapGenerator:
  - name: podinfo-values
    files:
      - values.yaml=values.yaml
patches:
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: podinfo
        namespace: podinfo
      spec:
        valuesFrom:
          - kind: ConfigMap
            name: podinfo-values
