apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd-jaeger
resources:
  - ../base
configMapGenerator:
  - name: linkerd-jaeger-values
    files:
      - values.yaml=values.yaml
patches:
  - patch: |
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: linkerd-jaeger
      spec:
        valuesFrom:
          - kind: ConfigMap
            name: linkerd-jaeger-values
