---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-with-kustomize
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./apps/podinfo-with-kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: podinfo-kustomization
